### ISSUE TITLE
Sorry I don't understand how to use github... I'm sorry if I make you mad.

### ISSUE THREAD

**Issue by Kysumer** [min2222/AlexsCaves-Backport#15]
Hello! I know its too soon to ask of you, and I'm sorry if this is annoying but I was just wondering if you're going to update this with the new 1.1.0 update? Really sorry about writing this in issues and asking this soon. I don't want to make you mad. Thank you!

**Comment by min2222** [comment]
completed
https://github.com/min2222/AlexsCaves-Backport/releases

**Comment by kitovoi111** [comment]
thank!!!!!!!!!!!!!!!!!!
