### ISSUE TITLE
[Bug] alexsmobs:dimensional_carver + dinosaur teleportation

### ISSUE THREAD

**Issue by kitovoi111** [min2222/AlexsCaves-Backport#4]
When I sit on a dinosaur and try to go into the portal created by alexsmobs:dimensional_carver - then when I teleport on a dinosaur - it is not visible and I can’t do anything, I have to restart the game

**Comment by min2222** [comment]
can you test with other ridable mobs?

**Comment by kitovoi111** [comment]
> can you test with other ridable mobs?

yes. wait bro.

**Comment by kitovoi111** [comment]
Problem alex's mobs.
