### ISSUE TITLE
[Bug] alexscaves:cave_book formatting gone wrong

### ISSUE THREAD

**Issue by kitovoi111** [min2222/AlexsCaves-Backport#6]
![image](https://github.com/min2222/AlexsCaves-Backport/assets/147491823/00bf699c-16a5-4b47-856a-0eda3a98d82f)

**Comment by min2222** [comment]
![2024-01-21_12 31 13](https://github.com/min2222/AlexsCaves-Backport/assets/73619004/4cf20320-de03-4105-8cb0-539b5c46f88e)

might be issue with other mod
