### ISSUE TITLE
[Feature Request] [Bug] alexscaves:quarry_smasher destroy any block (lootr chests, unbreakeable spawners)

### ISSUE THREAD

**Issue by kitovoi111** [min2222/AlexsCaves-Backport#7]
I have the Lootr and Unbreakeable Spawners mod, which does not allow these blocks to break from anything, neither from explosions nor from breakdowns. But for some reason the quarry breaks all these blocks, could you help me do the integration check, please? alexscaves:quarry_smasher destroy any block

mods: https://legacy.curseforge.com/minecraft/mc-mods/unbreakable-spawner/files
and https://legacy.curseforge.com/minecraft/mc-mods/lootr

**Comment by min2222** [comment]
this is exist in 1.20.1 version too, better for ask to alex or lootr developer

**Comment by kitovoi111** [comment]
Is there no way to add a check to the quarry itself? For example, the IC2 Classic mod already has a built-in check, for example in an electric miner

**Comment by min2222** [comment]
not that hard, but i'll wait for response from alex, and how he changed the code.

**Comment by kitovoi111** [comment]
> not that hard, but i'll wait for response from alex, and how he changed the code.

thank you.

**Comment by kitovoi111** [comment]
![image](https://github.com/min2222/AlexsCaves-Backport/assets/147491823/63c98ad6-9051-41fe-89b8-5ef14a7bd997)
Lootr developer response

**Comment by kitovoi111** [comment]
All hope is for you)
